// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Dome

#ifndef _DOME_UI_H
#define _DOME_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void Notice_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_time2;
extern lv_obj_t * ui_ber;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_base;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_dianchi_png);    // assets\dianchi.png
LV_IMG_DECLARE(ui_img_1801474518);    // assets\wifi-fill-20.png
LV_IMG_DECLARE(ui_img_234108997);    // assets\base-station-fill-20.png
LV_IMG_DECLARE(ui_img_loch_png);    // assets\loch.png
LV_IMG_DECLARE(ui_img_2086051052);    // assets\msg-2.png
LV_IMG_DECLARE(ui_img_ale_png);    // assets\ale.png

LV_FONT_DECLARE(ui_font_PingFang16s4bbp);
LV_FONT_DECLARE(ui_font_PingFang26s4bbp);
LV_FONT_DECLARE(ui_font_font);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
